### PR TITLE
Release: v1.2.1

### PR DESCRIPTION
**Pull request by grisadiche**
### Summary

[SC-3362](https://app.shortcut.com/kestrel/story/3362/better-recent-comments-test-and-declare-compatibility-with-wp6-6-1)

This is the release branch for version 1.2.1

### Details

- [X] Bump versions (readme/changelog/main plugin file)
- [ ] Edit changelog with correct release date

### CODE REVIEW

**Comment by maxrice** [comment]
@grisadiche I think for compatibility testing we can simply update the readme.txt, rather than doing a new plugin release.  @unfulvio can you help Andrew with this?

**Comment by unfulvio** [comment]
@maxrice @grisadiche sure I can merge as is or w/o version bump... may I know why a release was necessary? seems this was prompted by a story by @IanMisnerThough -- what's the expectation?

**Comment by grisadiche** [comment]
@unfulvio - the expectation is only to declare compatibility with the current WP version. We should merge w/o the version bump like @maxrice recommended!

**Comment by maxrice** [comment]
@grisadiche can you close this PR and open another with just the "tested up to" changed in both the plugin file _and_ readme.txt? I can review + approve that and then when we merge to `master`, the GH action should automatically depoy the change to wordpress.org for us. thanks!

**Comment by grisadiche** [comment]
closing PR per @maxrice recommendation. New PR opened to update plugin and readme files only.

**Pull request closed without merging**
